runtime:
  cache_dir: ./.cache/antora

site:
  title: Knative Workshop
  url: https://redhat-developer-demos.github.io/knative-tutorial
  start_page: knative-tutorial::index.adoc

content:
  sources:
    - url: git@github.com:redhat-developer-demos/knative-tutorial.git
      branches: 
       - workshop/0.4
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: $WORKSHOP_USER-knativetutorial
    title: Knative Workshop
    etherPad: http://etherpad-etherpad.apps.ws.ocp4dp.nosue.mobi
    apiUrl: https://api.ws.ocp4dp.nosue.mobi:6443 
    workshop: true
    workshop-domain: knative-workshop.devx.red
    workshop-version: release/0.4
  extensions:
    - ./lib/copy-to-clipboard.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
