apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: greeter
spec:
  revisionTemplate:
    metadata:
      annotations:
        # disable istio-proxy injection
        sidecar.istio.io/inject: "false"
      labels:
        app: greeter
    spec:
      container:
        image: dev.local/rhdevelopers/greeter:0.0.1
        env:
          - name: MESSAGE_PREFIX
            value: Namaste
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
