apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: greeter-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      revision: master
      url: https://github.com/redhat-developer-demos/knative-tutorial-greeter.git
  steps:
    - args:
        - --context=/workspace/java/springboot
        - --dockerfile=/workspace/java/springboot/Dockerfile.all
        - --destination=docker.io/kameshsampath/greeter:0.0.1
      env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
      image: gcr.io/kaniko-project/executor
      name: docker-push
      volumeMounts:
        - mountPath: /builder/home/.m2
          name: m2-cache
        - mountPath: /cache
          name: kaniko-cache
      workingDir: /workspace/java/springboot
  timeout: 20m
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache
