apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: messages-us
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: messages-others
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
