apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            # disable istio-proxy injection
            sidecar.istio.io/inject: "false"
          labels:
            app: event-greeter
        spec:
          container:
            image: $destinationImageName
