name: Knative Tutorial Staging

on:
  push:
    branches: 
      - master
env:
  SITE_DIR: 'gh-pages'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: staging.yaml
#       - name: "List folder"
#         run: |
#            ls -ltr $GITHUB_WORKSPACE/
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_site]
    name: "Deploy to Staging"
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         repository: redhat-developer-docs/knative-tutorial-staging
         ref: 'gh-pages'
         path: knative-tutorial-staging
     - name: "List folder"
       run: |
           ls -ltr $GITHUB_WORKSPACE/
     - name: Download generated site
       uses: actions/download-artifact@v1
       with:
         name: site
         path: "${{ github.workspace }}/knative-tutorial-staging/${{ env.SITE_DIR }}"
     - name: Deploy to GitHub Pages
       uses: JamesIves/github-pages-deploy-action@3.2.1
       with:
        ACCESS_TOKEN: " ${{ secrets.GITHUB_PAT }}"
        FOLDER: "knative-tutorial-staging/${{ env.SITE_DIR }}"
        BRANCH: 'gh-pages'
        COMMIT_MESSAGE: "[Staging] Publish Documentation for ${{ github.sha }}"
